BINARY_NAME=magiceightball

all: docker-build
docker-build:
	docker build -t nemonik/magiceightball .

#clean:
#	rm -f $(BINARY_NAME)
#fmt:
#	$(GOFMT)
#lint: fmt
#	$(GOGET) golang.org/x/lint/golint
#	golint
#test: lint
#	$(GOTEST) -v -cover ./...
#build: test
#	$(GOBUILD) -o $(BINARY_NAME) -v
#run:
#	./$(BINARY_NAME)

